# @package _global_
hydra:
  run:
    dir: ./outputs/${main_operation_mode}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${main_operation_mode}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}